[hotfix] Fix undefined reference error
Liking skia library returns following error because
tizen platform doesn't support the function egl_get_gl_proc.

>> /usr/lib/skia/libskia_skgpu.a(skgpu.GrGLCreateNativeInterface_egl.o):
>> function egl_get_gl_proc(void*, char const*):
>> error: undefined reference to 'eglGetProcAddress'

So, until tizen platform supports it, it needs to be ignored.

Bug: http://suprem.sec.samsung.net/jira/browse/TWF-1257

Change-Id: I5ba56165fa0e44202abe352a1f34ba6d49310f0c
Signed-off-by: Youngsoo Choi <kenshin.choi@samsung.com>